image: garthk/qt-build:bionic-5.12.0
stages:
    - build
    - push-latest

variables:
    DOCKER_IMAGE:        ${CI_REGISTRY_IMAGE}:${CI_BUILD_REF_NAME}
    DOCKER_LATEST_IMAGE: ${CI_REGISTRY_IMAGE}:latest

#
# Build a docker image using the files in the 'docker/' subdirectory.
#
build:
    stage: build
    # указываем образ в котором будет происходить сборка
    image: garthk/qt-build:bionic-5.12.0
    
    # указываем команды для сборки
    script:
    - qmake -makefile
    - make
    
    # загружаем собранные файлы в gitlab
    artifacts:
        paths:
            - ./build

#
# Tag the master image as 'latest'.
#
#push-latest:
    #stage: push-latest
    #script:
#        - docker pull ${DOCKER_IMAGE}
#        - docker tag ${DOCKER_IMAGE} ${DOCKER_LATEST_IMAGE}
#        - docker push ${DOCKER_LATEST_IMAGE}
#    only:
#        - master