stages:
    - build
    - push-latest

build:
    stage: build
    # указываем образ в котором будет происходить сборка
    image: garthk/qt-build:bionic-5.12.0
    
    # указываем команды для сборки
    script:
    - qmake -makefile
    - make
    
    # загружаем собранные файлы в gitlab
    artifacts:
        paths:
            - ./build

#
# Tag the master image as 'latest'.
#
#push-latest:
    #stage: push-latest
    #script:
#        - docker pull ${DOCKER_IMAGE}
#        - docker tag ${DOCKER_IMAGE} ${DOCKER_LATEST_IMAGE}
#        - docker push ${DOCKER_LATEST_IMAGE}
#    only:
#        - master