stages:
    - build

build-win64:
    stage: build
    image: burningdaylight/docker-mingw-qt5 #image: garthk/qt-build:bionic-5.12.0
    script:
        - x86_64-w64-mingw32-qmake-qt5
        - make -j$((`nproc`+1))
        # x86_64-w64-mingw32-windeployqt-qt5 -release
        # qmake -makefile
        # make -B /builds/DrSasha/idea-craft/Makefile
    artifacts:
        paths:
            - iDeA-Craft.exe

build-lin64:
    stage: build
    image: fffaraz/qt:latest
    script:
        - x86_64-linux-gnu-qmake
        - make -j$((`nproc`+1))
    artifacts:
        paths:
            - idea-craft
