image: burningdaylight/docker-mingw-qt5
stages:
    - build
    - push-latest

build:
    stage: build
    # указываем образ в котором будет происходить сборка
    # image: garthk/qt-build:bionic-5.12.0
    
    # указываем команды для сборки
    script:
    - cd /builds/DrSasha/idea-craft
    - x86_64-w64-mingw32-qmake-qt5
    - make
    - mkdir build
    - cp iDeA-Craft.exe build/iDeA-Craft.exe
    # x86_64-w64-mingw32-windeployqt-qt5 -release
    # qmake -makefile
    # make -B /builds/DrSasha/idea-craft/Makefile
    # i686-w64-mingw32-qmake-qt5
    
    # загружаем собранные файлы в gitlab
    artifacts:
        paths:
            - ./build

#
# Tag the master image as 'latest'.
#
#push-latest:
    #stage: push-latest
    #script:
#        - docker pull ${DOCKER_IMAGE}
#        - docker tag ${DOCKER_IMAGE} ${DOCKER_LATEST_IMAGE}
#        - docker push ${DOCKER_LATEST_IMAGE}
#    only:
#        - master