version: 2
jobs:
    build-win64:
        working_directory: /tmp/idea
        docker:
            - image: burningdaylight/docker-mingw-qt5 # указываем образ в котором будет происходить сборка
            #- image: therecipe/qt:windows_64_shared
        steps:
            - checkout
            - run:
                name: Windows build
                command: x86_64-w64-mingw32-qmake-qt5 && make -j$((`nproc`+1))
            - run:
                name: Print the Current Time
                command: date && date > win64.time
            - save_cache:
                paths:
                    - win64.time
                    - iDeA-Craft.exe
                key: win64-build-{{ .Environment.CIRCLE_SHA1 }}
            - store_artifacts:
                path: iDeA-Craft.exe
    build-linux64:
        working_directory: /tmp/idea
        docker:
            - image: devsasha/qt-xbuild:linux #fffaraz/qt:latest # vookimedlo/ubuntu-qt
              user: nonroot
        steps:
            - checkout
            - run:
                name: Linux build
                command: qmake && make -j$((`nproc`+1))
            - run:
                name: Print the Current Time
                command: date && date > linux64.time
            - save_cache:
                paths:
                    - iDeA-Craft
                    - linux64.time
                key: linux64-build-{{ .Environment.CIRCLE_SHA1 }}
            - store_artifacts:
                path: iDeA-Craft
    make-deb-stable:
        working_directory: /tmp/idea
        docker:
            - image: 0xef53/deb-builder:stretch
        steps:
            - checkout
            - run:
                name: Add HTTPS support in wget? TODO=move to Dockerfile
                command: apt update && apt install -y openssl ca-certificates
            - restore_cache:
                key: linux64-build-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                name: Makedeb
                command: chmod +x deploy/mkdeb && deploy/mkdeb
            - run:
                name: Copy in afrtifacts
                command: mkdir -p build/linux64 && cp idea-craft.deb build/linux64/idea-craft_0.0.2-10_amd64.deb
            - save_cache:
                paths:
                    - build/linux64
                key: linux64-deb-{{ .Environment.CIRCLE_SHA1 }}
            - store_artifacts:
                path: build/linux64
    make-deb-tested:
        working_directory: /tmp/idea
        docker:
            - image: 0xef53/deb-builder:stretch
        steps:
            - checkout
            - run:
                name: Add HTTPS support in wget? TODO=move to Dockerfile
                command: apt update && apt install -y openssl ca-certificates
            - restore_cache:
                key: linux64-build-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                name: Change deb package version
                command: 'cd deploy/DEBIAN && sed -i 2d control && sed -i 2iVersion:0.0.2-10 control'
            - run: 
                name: Makedeb
                command: chmod +x deploy/mkdeb && deploy/mkdeb
            - run:
                name: Copy in afrtifacts
                command: mkdir -p build/linux64 && cp idea-craft.deb build/linux64/idea-craft_0.0.2-10_amd64.deb
            - save_cache:
                paths:
                    - build/linux64
                key: linux64-deb-{{ .Environment.CIRCLE_SHA1 }}
            - store_artifacts:
                path: build/linux64
    make-deb-dev:
        working_directory: /tmp/idea
        docker:
            - image: 0xef53/deb-builder:stretch
        steps:
            - checkout
            - run:
                name: Add HTTPS support in wget? TODO=move to Dockerfile
                command: apt update && apt install -y openssl ca-certificates curl wget
            - restore_cache:
                key: linux64-build-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                name: Change deb package version
                command: VER=$(curl 'http://api.idea-craft.space/launcher/getTargetVersion.php?branch=dev&format=deb') |
                         cd deploy/DEBIAN && sed -i 2d control && sed -i 2iVersion:${VER} control
            - run:
                name: Makedeb
                command: chmod +x deploy/mkdeb && deploy/mkdeb
            - run:
                name: Copy in afrtifacts
                command: mkdir -p build/linux64 && cp idea-craft.deb build/linux64/idea-craft_${VER}_amd64.deb
            - save_cache:
                paths:
                    - build/linux64
                key: linux64-deb-{{ .Environment.CIRCLE_SHA1 }}
            - store_artifacts:
                path: build/linux64
    deploy:
        working_directory: /tmp/idea
        docker:
            - image: ubuntu
        steps:
            - run:
                name: Add HTTPS support in wget? TODO=move to Dockerfile
                command: apt update && apt install -y openssl ca-certificates
            - restore_cache:
                key: linux64-deb-{{ .Environment.CIRCLE_SHA1 }}
            - restore_cache:
                key: win64-build-{{ .Environment.CIRCLE_SHA1 }}
            - run: mkdir -p build/win64/ && cp iDeA-Craft.exe build/win64/
            - store_artifacts:
                path: build
workflows:
    version: 2
    build-deploy:
        jobs:
            - build-linux64
            - build-win64
            - make-deb-stable:
                filters:
                    branches:
                        only: master
                requires:
                    - build-linux64
            - make-deb-tested:
                filters:
                    branches:
                        only: tested
                requires:
                    - build-linux64
            - make-deb-dev:
                filters:
                    branches:
                        only: dev
                requires:
                    - build-linux64
            - deploy:
                requires:
                    - build-win64
                    - make-deb-stable
                    - make-deb-tested
                    - make-deb-dev