version: 2
jobs:
    build-win64:
        docker:
            - image: burningdaylight/docker-mingw-qt5 # указываем образ в котором будет происходить сборка
            #- image: therecipe/qt:windows_64_shared
        steps:
            - checkout
            - run:
                name: Windows build
                command: x86_64-w64-mingw32-qmake-qt5 && make -j$((`nproc`+1))
            - run:
                name: Print the Current Time
                command: date && date > win64.time
            - save_cache:
                paths:
                    - iDeA-Craft.exe
                key: win64-build-${CIRCLE_SHA1}
    build-linux64:
        docker:
            - image: devsasha/qt-xbuild:linux #fffaraz/qt:latest # vookimedlo/ubuntu-qt
              user: nonroot
        steps:
            - checkout
            - run:
                name: Linux build
                command: qmake && make -j$((`nproc`+1))
            - run:
                name: Print the Current Time
                command: date && date > linux64.time
            - save_cache:
                paths:
                    - deploy/
                    - iDeA-Craft
                    - linux64.time
                key: linux64-build-${CIRCLE_SHA1}
    deploy-deb-stable:
        docker:
            - image: 0xef53/deb-builder:stretch
        steps:
            - checkout
            - run:
                name: Add HTTPS support in wget? TODO=move to Dockerfile
                command: apt install -y openssl ca-certificates
            - restore_cache:
                key: linux64-build-${CIRCLE_SHA1}
            - run:
                name: Makedeb
                command: chmod +x deploy/mkdeb && deploy/mkdeb
            - run:
                name: Copy in afrtifacts
                command: cp idea-craft.deb build/linux64/idea-craft_0.0.2-10_amd64.deb
            - store_artifacts:
                path: build/linux64
    deploy-deb-tested:
        docker:
            - image: 0xef53/deb-builder:stretch
        steps:
            - checkout
            - run:
                name: Add HTTPS support in wget? TODO=move to Dockerfile
                command: apt install -y openssl ca-certificates
            - restore_cache:
                key: linux64-build-${CIRCLE_SHA1}
            - run:
                name: Change deb package version
                command: 'sed -i 2d control && sed -i 2iVersion:0.0.2-10 deploy/DEBIAN/control'
            - run: 
                name: Makedeb
                command: chmod +x deploy/mkdeb && deploy/mkdeb
            - run:
                name: Copy in afrtifacts
                command: cp idea-craft.deb build/linux64/idea-craft_0.0.2-10_amd64.deb
            - store_artifacts:
                path: build/linux64
    deploy-deb-dev:
        docker:
            - image: 0xef53/deb-builder:stretch
        steps:
            - checkout
            - run:
                name: Add HTTPS support in wget? TODO=move to Dockerfile
                command: apt install -y openssl ca-certificates
            - restore_cache:
                key: linux64-build-${CIRCLE_SHA1}
            - run:
                name: Change deb package version
                command: 'sed -i 2d control && sed -i 2iVersion:0.0.2-10 deploy/DEBIAN/control'
            - run: 
                name: Makedeb
                command: chmod +x deploy/mkdeb && deploy/mkdeb
            - run:
                name: Copy in afrtifacts
                command: cp idea-craft.deb build/linux64/idea-craft_0.0.2-10_amd64.deb
            - store_artifacts:
                path: build/linux64
workflows:
    version: 2
    build-deploy:
        jobs:
            - build-linux64
            - build-win64
            - deploy-deb-stable:
                filters:
                    branches:
                        only: master
                requires:
                    - build-linux64
            - deploy-deb-tested:
                filters:
                    branches:
                        only: tested
                requires:
                    - build-linux64
            - deploy-deb-dev:
                filters:
                    branches:
                        only: dev
                requires:
                    - build-linux64