version: 2
jobs:
    build-win64:
        working_directory: /tmp/idea
        docker:
            - image: burningdaylight/docker-mingw-qt5 # указываем образ в котором будет происходить сборка
            #- image: therecipe/qt:windows_64_shared
        steps:
            - checkout
            - run:
                name: Windows build
                command: x86_64-w64-mingw32-qmake-qt5 && make -j$((`nproc`+1))
            - run:
                name: Move bin files in one dir
                command: mkdir -p win64/ && mv idea-craft.exe win64/client && mv idea-server.exe win64/server
            - run:
                name: Print the Current Time
                command: date && date > win64/win64.time
            - save_cache:
                paths:
                    - win64/
                key: win64-build-{{ .Environment.CIRCLE_SHA1 }}
            - store_artifacts:
                path: win64/
    deploy-win64:
        working_directory: /tmp/idea/win64
        docker:
            - image: ubuntu
        steps:
            - run:
                name: Add HTTPS support in wget? TODO=move to Dockerfile
                command: apt update && apt install -y openssl ca-certificates curl wget
            - restore_cache:
                key: win64-build-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                name: Check sum of all files of client
                command: find client -type f -exec sha256sum {} \; > client.sha256
            - run:
                name: Check sum of all files of server
                command: find server -type f -exec sha256sum {} \; > server.sha256
            - save_cache:
                paths:
                    - .
                key: win64-deploy-{{ .Environment.CIRCLE_SHA1 }}
            - store_artifacts:
                path: .
    build-linux64:
        working_directory: /tmp/idea
        docker:
            - image: devsasha/qt-xbuild:linux #fffaraz/qt:latest # vookimedlo/ubuntu-qt
              user: nonroot
        steps:
            - checkout
            - run:
                name: Linux build
                command: qmake && make -j$((`nproc`+1))
            - run:
                name: Move bin files in one dir
                command: mkdir -p linux64/ && mv idea-craft linux64/client && mv idea-server server/
            - run:
                name: Print the Current Time
                command: date && date > linux64/linux64.time
            - save_cache:
                paths:
                    - linux64/
                key: linux64-build-{{ .Environment.CIRCLE_SHA1 }}
            - store_artifacts:
                path: linux64/
    deploy-linux64:
        working_directory: /tmp/idea/linux64
        docker:
            - image: ubuntu
        steps:
            - run:
                name: Add HTTPS support in wget? TODO=move to Dockerfile
                command: apt update && apt install -y openssl ca-certificates curl wget
            - restore_cache:
                key: linux64-build-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                name: Check sum of all files of client
                command: find client -type f -exec sha256sum {} \; > client.sha256
            - run:
                name: Check sum of all files of server
                command: find server -type f -exec sha256sum {} \; > server.sha256
            - save_cache:
                paths:
                    - .
                key: linux64-deploy-{{ .Environment.CIRCLE_SHA1 }}
            - store_artifacts:
                path: .
    make-deb:
        working_directory: /tmp/idea
        docker:
            - image: 0xef53/deb-builder:stretch
        steps:
            - checkout
            - run:
                name: Add HTTPS support in wget? TODO=move to Dockerfile
                command: apt update && apt install -y openssl ca-certificates curl wget
            - restore_cache:
                key: linux64-build-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                name: Setup workspace
                command: mkdir -p {client,server} && mv idea-craft.exe client/ && mv idea-server.exe server/
            - run:
                name: Get target version
                command: |
                    VER=$(curl 'http://api.idea-craft.space/launcher/getTargetVersion.php?branch='${CIRCLE_BRANCH}'&format=deb') &&
                    echo $VER &&
                    echo 'export VER='$VER'' >> $BASH_ENV &&
                    cat $BASH_ENV
            - run:
                name: Change deb package version
                command: 'cd deploy/DEBIAN && sed -i 2d control && sed -i 2iVersion:${VER} control'
            - run:
                name: Makedeb
                command: chmod +x deploy/mkdeb && deploy/mkdeb
            - run:
                name: Copy in afrtifacts
                command: mkdir -p build/linux64 && cp idea-craft.deb build/linux64/idea-craft_${VER}_amd64.deb
            - save_cache:
                paths:
                    - build/linux64
                key: linux64-deb-{{ .Environment.CIRCLE_SHA1 }}
            - store_artifacts:
                path: build/linux64
    delivery:
        working_directory: /tmp/idea
        docker:
            - image: ubuntu
        steps:
            - run:
                name: Add HTTPS support in wget? TODO=move to Dockerfile
                command: apt update && apt install -y openssl ca-certificates
            - restore_cache:
                key: linux64-deploy-{{ .Environment.CIRCLE_SHA1 }}
            - restore_cache:
                key: win64-deploy-{{ .Environment.CIRCLE_SHA1 }}
            - run: 
                name: Specify branch
                command: echo "${CIRCLE_BRANCH}" >> branch
            - store_artifacts:
                path: .
            - run: echo $VER'-'$BASH_ENV
workflows:
    version: 2
    build-deploy:
        jobs:
            - build-linux64
            - build-win64
            - deploy-win64:
                requires:
                    - build-win64
                filters:
                    branches:
                        only: 
                            - master
                            - tested
                            - dev
            - deploy-linux64:
                requires:
                    - build-linux64
                filters:
                    branches:
                        only: 
                            - master
                            - tested
                            - dev
            # - make-deb:
            #     filters:
            #         branches:
            #             only: 
            #                 - master
            #                 - tested
            #                 - dev
            #     requires:
            #         - build-linux64
            - delivery:
                requires:
                    - deploy-win64
                    - deploy-linux64
                   # - make-deb