version: 2
jobs:
  build:
    docker: 
      - image: therecipe/qt:windows_64_shared

    steps:
      - checkout

      - run:
          name: Building
          command: qtdeploy

      - run:
          name: Print the Current Time
          command: date