version: 2
jobs:
  build:
    docker:
      - image: garthk/qt-build:bionic-5.12.0

    steps:
      - checkout

      - run:
          name: Building
          command: qmake -makefile && make

      - run:
          name: Print the Current Time
          command: date