version: 2
jobs:
    build-win64:
        docker: 
            - image: burningdaylight/docker-mingw-qt5 # указываем образ в котором будет происходить сборка
            #- image: therecipe/qt:windows_64_shared
        steps:
            - checkout
            - run: x86_64-w64-mingw32-qmake-qt5
            - run: make -j$((`nproc`+1)) 
            - run: mkdir -p build/win64
            - run: cp iDeA-Craft.exe build/win64/iDeA-Craft-x64.exe
            - run:
                name: Print the Current Time
                command: date
            - store_artifacts:
                path: build/win64
    build-linux64:
        docker: 
            - image: devsasha/qt-xbuild:linux #fffaraz/qt:latest # vookimedlo/ubuntu-qt
              user: nonroot
        steps:
            - checkout
            - run: 
                name: Linux build
                command: qmake && make -j$((`nproc`+1)) 
            - run:
                name: Setup enviroment for Linux deploy
                command: mkdir -p build/linux64
            - run: 
                name: Makedeb
                command: chmod +x deploy/mkdeb && deploy/mkdeb
            - run:
                name: Check deb
                command: lintian idea-craft.deb > build/linux64/lintian.list 
            - run:
                name: Copy in afrtifacts
                command: cp -R idea-craft build/linux64/ && cp idea-craft.deb build/linux64/idea-craft_0.0.2-10_amd64.deb
                #command: mkdir -p build/linux64 && cp iDeA-Craft build/linux64/idea-craft
            - store_artifacts:
                path: build/linux64
workflows:
    version: 2
    build-deploy:
        jobs:
            - build-linux64
            - build-win64
    
