version: 2
jobs:
  build:
    docker: 
      - image: burningdaylight/docker-mingw-qt5 # указываем образ в котором будет происходить сборка
      #- image: therecipe/qt:windows_64_shared

    steps:
      - checkout

      - run:
          name: Building
          command: 

      - run:
          name: Print the Current Time
          command: date