#!/bin/bash
mkdir -p idea-craft/{DEBIAN,usr/{bin,share/{applications,icons/hicolor}},opt/idea-craft}
cp iDeA-Craft idea-craft/opt/idea-craft/idea-craft
cp deploy/DEBIAN/* idea-craft/DEBIAN/
cp deploy/idea-craft.desktop idea-craft/usr/share/applications/
fakeroot dpkg-deb --build idea-craft
